---
:api_key: '089d2cca04f0ef8a9584a0eb3b3680e5'
:password: 6d7c295b5f6c0dea99e8f7be8189d6da
:theme_id: '11'
:preview_url: https://www.mojaveoficial.com.br/loja/loja.php?loja=747062&opencode_theme=5ea83d8b52d4f
