---
:api_key: '089d2axa04f0ef1a9574a0eb3b3780e4'
:password: '7d7c294b5f6c0dxa999e8f7be819d6da'
:theme_id: '11'
:preview_url: 'https://www.mojaveoficial.com.br/loja/loja.php?loja=747062&opencode_theme=5ea83d8b52d4f'
