---
:api_key: '089d2axa*********************'
:password: '7d7c294***********************'
:theme_id: '11'
:preview_url: 'https://www.mojaveoficial.com.br/loja/loja.php?loja=747062&opencode_theme=*************'
